language: java

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2/

# https://docs.travis-ci.com/user/job-lifecycle/#skipping-the-installation-phase use gradlew commands in this project, so skipping the installation phase
install: skip

script:
  - ./mvnw -B clean test
